### ISSUE TITLE
Path too long error

### ISSUE THREAD

**Issue by sickler-alex** [hubmapconsortium/salmon-rnaseq#14]
Hello, I'm testing the pipeline on Cavatica and I am getting an error from the scvelo-analysis step. The full error is below. I believe the error is either from the path to the input file used being very long or that a temp directory is getting created that is very long.

This is the error that I am getting:
```
2021-10-29T19:36:51.696769245Z Process SyncManager-1:
2021-10-29T19:36:51.696797971Z Traceback (most recent call last):
2021-10-29T19:36:51.696802596Z   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
2021-10-29T19:36:51.696806892Z     self.run()
2021-10-29T19:36:51.696810636Z   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
2021-10-29T19:36:51.696814597Z     self._target(*self._args, **self._kwargs)
2021-10-29T19:36:51.696819158Z   File "/usr/lib/python3.8/multiprocessing/managers.py", line 608, in _run_server
2021-10-29T19:36:51.696824771Z     server = cls._Server(registry, address, authkey, serializer)
2021-10-29T19:36:51.696831205Z   File "/usr/lib/python3.8/multiprocessing/managers.py", line 154, in __init__
2021-10-29T19:36:51.696836853Z     self.listener = Listener(address=address, backlog=16)
2021-10-29T19:36:51.696842333Z   File "/usr/lib/python3.8/multiprocessing/connection.py", line 448, in __init__
2021-10-29T19:36:51.696848579Z     self._listener = SocketListener(address, family, backlog)
2021-10-29T19:36:51.696854610Z   File "/usr/lib/python3.8/multiprocessing/connection.py", line 591, in __init__
2021-10-29T19:36:51.696860801Z     self._socket.bind(address)
2021-10-29T19:36:51.696866116Z OSError: AF_UNIX path too long
2021-10-29T19:36:51.708503336Z Traceback (most recent call last):
2021-10-29T19:36:51.708533374Z   File "/opt/scvelo_analysis.py", line 65, in <module>
2021-10-29T19:36:51.708539176Z     main(args.alevin_h5ad_file)
2021-10-29T19:36:51.708543038Z   File "/opt/scvelo_analysis.py", line 35, in main
2021-10-29T19:36:51.708547213Z     scv.tl.recover_dynamics(adata)
2021-10-29T19:36:51.708551132Z   File "/usr/local/lib/python3.8/dist-packages/scvelo/tools/dynamical_model.py", line 501, in recover_dynamics
2021-10-29T19:36:51.708555346Z     res = parallelize(
2021-10-29T19:36:51.708559350Z   File "/usr/local/lib/python3.8/dist-packages/scvelo/core/_parallelize.py", line 122, in wrapper
2021-10-29T19:36:51.708574474Z     queue = Manager().Queue()
2021-10-29T19:36:51.708580115Z   File "/usr/lib/python3.8/multiprocessing/context.py", line 57, in Manager
2021-10-29T19:36:51.708587361Z     m.start()
2021-10-29T19:36:51.708592926Z   File "/usr/lib/python3.8/multiprocessing/managers.py", line 583, in start
2021-10-29T19:36:51.708598793Z     self._address = reader.recv()
2021-10-29T19:36:51.708604543Z   File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
2021-10-29T19:36:51.708610432Z     buf = self._recv_bytes()
2021-10-29T19:36:51.708615879Z   File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
2021-10-29T19:36:51.708620030Z     buf = self._recv(4)
2021-10-29T19:36:51.708623583Z   File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
2021-10-29T19:36:51.708627337Z     raise EOFError
2021-10-29T19:36:51.708630940Z EOFError
```

**Comment by sickler-alex** [comment]
Investigating this more, I think add this to the hints section will get around this issue:
```
  InitialWorkDirRequirement:
    listing: [$(inputs.spliced_h5ad_file)]
  EnvVarRequirement:
    envDef:
      TMPDIR: "/tmp"
```

If you would like, I can create a PR with this change

**Comment by migbro** [comment]
It seems I have re-discovered this error upon testing the latest release. The solution can be further simplified it seems to:
```
  - class: EnvVarRequirement
    envDef:
      TMPDIR: "/tmp"
```
Perhaps, if hardciding the TMPDIR path makes one uneasy, an optional variable with a default could be uses I think
